package org.i2i;

import java.sql.*;
import java.util.Random;
import java.util.UUID;

public class Main {

    /**
     * @param args
     */
    public static void main(String[] args)
    {
        //  throws SQLException

        //initiazlie the connection

        Connection con=null;

        try //try connection to database
        {
            //load driver
            Class.forName("oracle.jdbc.OracleDriver");
            System.out.println("Oracle JDBC driver loaded ok.");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/orclpdb1", "system", "oracle");
            System.out.println("Connect with @oracle:1521:orcl");

            //declaring statement
            Statement stmt = con.createStatement();

            try {
                stmt.executeUpdate("DROP TABLE BOOK");
                System.out.println("Existing BOOK table dropped.");
            } catch (SQLException e) {
                System.out.println("BOOK table does not exist, skipping drop.");
            }

            // Create BOOK table
            String createBookTable = "CREATE TABLE BOOK (" +
                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "NAME VARCHAR2(100), " +
                    "ISBN VARCHAR2(20))";

            stmt.executeUpdate(createBookTable);
            System.out.println("BOOK table created.");

            // Insert 100 random records
            String insertSQL = "INSERT INTO BOOK (NAME, ISBN) VALUES (?, ?)";
            PreparedStatement pstmt = con.prepareStatement(insertSQL);

            for (int i = 1; i <= 100; i++) {
                String name = "Book_" + UUID.randomUUID().toString().substring(0, 8);
                String isbn = "ISBN" + (100000000 + new Random().nextInt(900000000));
                pstmt.setString(1, name);
                pstmt.setString(2, isbn);
                pstmt.executeUpdate();
            }

            System.out.println("100 random records inserted into BOOK table.");

            ResultSet rs = stmt.executeQuery("SELECT * FROM BOOK FETCH FIRST 10 ROWS ONLY");

            while (rs.next()) {
                System.out.println("ID: " + rs.getInt("ID") +
                        ", NAME: " + rs.getString("NAME") +
                        ", ISBN: " + rs.getString("ISBN"));
            }

            rs.close();
            pstmt.close();
            stmt.close();
            con.close();

        }
        catch (Exception e)
        {
            System.err.println("Exception:"+e.getMessage());
        }


    }

}
